UPDATE [PRODUTOS]
SET [COD_PRODUTO] = '01' 
WHERE [COD_PRODUTO] = '1'

UPDATE [PRODUTOS]
SET [COD_PRODUTO] = '02' 
WHERE [COD_PRODUTO] = '2'

UPDATE [PRODUTOS]
SET [COD_PRODUTO] = '03' 
WHERE [COD_PRODUTO] = '3'

UPDATE [PRODUTOS]
SET [COD_PRODUTO] = '04' 
WHERE [COD_PRODUTO] = '4'

UPDATE [PRODUTOS]
SET [COD_PRODUTO] = '05' 
WHERE [COD_PRODUTO] = '5'

UPDATE [PRODUTOS]
SET [COD_PRODUTO] = '06' 
WHERE [COD_PRODUTO] = '6'

UPDATE [PRODUTOS]
SET [COD_PRODUTO] = '07' 
WHERE [COD_PRODUTO] = '7'

UPDATE [PRODUTOS]
SET [COD_PRODUTO] = '08' 
WHERE [COD_PRODUTO] = '8'

UPDATE [PRODUTOS]
SET [COD_PRODUTO] = '09' 
WHERE [COD_PRODUTO] = '9'
